title: axh
description: Solve Important Problems, Create New Technology and Understand the Universe
url: "https://arihant-jha.github.io"
baseurl: ""
lang: en
timezone: Asia/Kolkata
permalink: /:year/:month/:day/:title/

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - deploy.sh
  - scripts
  - logs
  - .publish.lock
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
  - .jekyll-cache
